import type { VercelRequest, VercelResponse } from "@vercel/node";

/**
 * CSP Violation Report Collector (Vercel Serverless Function)
 *
 * Receives CSP violation reports from browsers via report-uri and report-to
 * directives. Filters out browser-extension noise and only alerts on
 * security-relevant violations (script-src, frame-src) on the donation domain.
 *
 * Reports are logged to stdout for ingestion by Vercel Log Drains / Sentry,
 * which should be wired to #security-incidents.
 *
 * PCI DSS SAQ A-EP — TT-F1 remediation (GIV-328).
 */

// Directives that indicate potentially malicious tampering on the payment page
const HIGH_RISK_DIRECTIVES = new Set([
  "script-src",
  "script-src-elem",
  "script-src-attr",
  "frame-src",
  "object-src",
  "base-uri",
]);

// URI patterns generated by browser extensions — never actionable
const EXTENSION_PATTERNS = [
  /^chrome-extension:\/\//,
  /^moz-extension:\/\//,
  /^safari-extension:\/\//,
  /^ms-browser-extension:\/\//,
  /^resource:\/\//,
  /^about:/,
];

interface CspReport {
  "document-uri"?: string;
  "violated-directive"?: string;
  "effective-directive"?: string;
  "blocked-uri"?: string;
  "source-file"?: string;
  "original-policy"?: string;
  disposition?: string;
  "status-code"?: number;
  referrer?: string;
  "script-sample"?: string;
}

interface ReportingApiBody {
  type?: string;
  age?: number;
  url?: string;
  user_agent?: string;
  body?: {
    documentURL?: string;
    violatedDirective?: string;
    effectiveDirective?: string;
    blockedURL?: string;
    sourceFile?: string;
    disposition?: string;
    statusCode?: number;
    sample?: string;
  };
}

function isExtensionUri(uri: string | undefined): boolean {
  if (!uri) return false;
  return EXTENSION_PATTERNS.some((p) => p.test(uri));
}

function isDonationPage(documentUri: string | undefined): boolean {
  if (!documentUri) return false;
  try {
    const url = new URL(documentUri);
    return (
      url.hostname.endsWith("giveprotocol.io") ||
      url.hostname === "localhost" ||
      url.hostname === "127.0.0.1"
    );
  } catch {
    return false;
  }
}

function normalizeReport(raw: unknown): {
  documentUri: string;
  effectiveDirective: string;
  blockedUri: string;
  sourceFile: string;
  disposition: string;
  sample: string;
} | null {
  if (!raw || typeof raw !== "object") return null;

  // Legacy report-uri format: { "csp-report": { ... } }
  const legacy = (raw as Record<string, unknown>)["csp-report"] as
    | CspReport
    | undefined;
  if (legacy) {
    return {
      documentUri: legacy["document-uri"] ?? "",
      effectiveDirective:
        legacy["effective-directive"] ?? legacy["violated-directive"] ?? "",
      blockedUri: legacy["blocked-uri"] ?? "",
      sourceFile: legacy["source-file"] ?? "",
      disposition: legacy.disposition ?? "enforce",
      sample: legacy["script-sample"] ?? "",
    };
  }

  // Reporting API v1 format: { type: "csp-violation", body: { ... } }
  const modern = raw as ReportingApiBody;
  if (modern.type === "csp-violation" && modern.body) {
    return {
      documentUri: modern.body.documentURL ?? modern.url ?? "",
      effectiveDirective:
        modern.body.effectiveDirective ??
        modern.body.violatedDirective ??
        "",
      blockedUri: modern.body.blockedURL ?? "",
      sourceFile: modern.body.sourceFile ?? "",
      disposition: modern.body.disposition ?? "enforce",
      sample: modern.body.sample ?? "",
    };
  }

  // Array of reports (Reporting API batches)
  if (Array.isArray(raw)) {
    // Process only the first report; browsers rarely batch CSP reports
    return normalizeReport(raw[0]);
  }

  return null;
}

export default function handler(req: VercelRequest, res: VercelResponse) {
  // Only accept POST
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed" });
    return;
  }

  // Accept both application/csp-report and application/reports+json
  const report = normalizeReport(req.body);
  if (!report) {
    // Acknowledge but ignore malformed reports
    res.status(204).end();
    return;
  }

  // --- Noise filtering ---

  // Drop browser-extension violations
  if (isExtensionUri(report.blockedUri) || isExtensionUri(report.sourceFile)) {
    res.status(204).end();
    return;
  }

  // Drop reports from non-Give-Protocol pages (stale tabs, etc.)
  if (!isDonationPage(report.documentUri)) {
    res.status(204).end();
    return;
  }

  // --- Severity classification ---

  const isHighRisk = HIGH_RISK_DIRECTIVES.has(report.effectiveDirective);

  // Always log for audit trail
  const logEntry = {
    level: isHighRisk ? "ALERT" : "INFO",
    event: "csp_violation",
    timestamp: new Date().toISOString(),
    directive: report.effectiveDirective,
    blockedUri: report.blockedUri,
    documentUri: report.documentUri,
    sourceFile: report.sourceFile,
    disposition: report.disposition,
    sample: report.sample.slice(0, 200),
    highRisk: isHighRisk,
  };

  if (isHighRisk) {
    // ALERT-level: these should reach #security-incidents via log drain
    console.error(
      `[CSP-ALERT] High-risk violation: ${report.effectiveDirective} blocked ${report.blockedUri} on ${report.documentUri}`,
    );
    console.error(JSON.stringify(logEntry));
  } else {
    console.log(JSON.stringify(logEntry));
  }

  // 204 No Content — browsers expect this
  res.status(204).end();
}
